---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Deploy Nginx configuration for Artifactory
  template:
    src: nginx.conf.j2  # Change this to your template file name
    dest: /etc/nginx/sites-available/artifactory
  become: true

- name: Create symbolic link for Nginx configuration
  file:
    src: /etc/nginx/sites-available/artifactory
    dest: /etc/nginx/sites-enabled/artifactory
    state: link
  become: true

- name: Test Nginx configuration
  command: nginx -t
  become: true

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: true



