---
- hosts: bastion
  become: true
  vars:
    bastionIp: "{{ lookup('file', '/var/lib/jenkins/workspace/Jfrog/terraform/bastion_ip.txt') }}"
    jfrogIp: "{{ lookup('file', '/var/lib/jenkins/workspace/Jfrog/terraform/jfrog_ip.txt') }}"
  roles:
    - nginx
- hosts: Jfrog
  become: yes
  roles:
    - jfrog_artifactory_install
